language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '8'
  - '9'
  - '10'

before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update
  - npm prune

script:
  - npm run coverage

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm run semantic-release

branches:
  only:
    - master
    - /^greenkeeper/.*$/
